name: 'Issue Duration Labeler'
description: 'Automatically label issues with color-coded duration tags, helping teams track issue lifecycle and improve project management.'
author: 'Mirek Lzicar'
inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  short_threshold:
    description: 'Number of days considered short duration (green label)'
    required: false
    default: '7'
  medium_threshold:
    description: 'Number of days considered medium duration (orange label)'
    required: false
    default: '30'
  short_color:
    description: 'Color for short duration labels'
    required: false
    default: '00FF00'
  medium_color:
    description: 'Color for medium duration labels'
    required: false
    default: 'FFA500'
  long_color:
    description: 'Color for long duration labels'
    required: false
    default: 'FF0000'
  thresholded_update:
    description: 'Update issue duration only when a threshold is met'
    required: false
    default: 'true'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'clock'
  color: 'blue'