name: Label Issues with Duration

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight every day
  workflow_dispatch:  # Allow manual triggering

jobs:
  label-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/issue-duration-labeler
        with:
          short_threshold: '3'
          medium_threshold: '10'
          short_color: '00FF00'
          medium_color: 'FFA500'
          long_color: 'FF0000'
