name: Label Issues with Duration

on:
  pull_request:
    types: [opened, synchronize, reopened]

  # Scheduled run on working days at 06:00 AM UTC (commented for initial testing)
  # schedule:
  #   - cron: '0 6 * * 1-5'  # Monday to Friday at 06:00 AM UTC

  workflow_dispatch:

jobs:
  label-issues:
    runs-on: ubuntu-latest
    name: Label Issues with Duration
    
    permissions:
      issues: write      # Allow adding/modifying labels on issues
      contents: read     # Minimal read access
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Label Issues with Duration
        uses: ./  # Use the local action in this repository
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue_state: 'all'           # Process all issues (open and closed)
          filter_label: ''             # Leave empty to process all issues, or set to specific label like 'ephemeral'
          short_threshold: '7'         # Issues 1-7 days old
          medium_threshold: '30'       # Issues 8-30 days old
          short_color: '00FF00'        # Green for short duration
          medium_color: 'FFA500'       # Orange for medium duration
          long_color: 'FF0000'         # Red for long duration (>30 days)
          thresholded_update: 'true'   # Only update when thresholds are crossed 